export const SupportAbi = [
  // --- Events ---
  {
    type: 'event',
    name: 'Supported',
    inputs: [
      { indexed: true, name: 'supporter', type: 'address' },
      { indexed: true, name: 'tier', type: 'uint8' },
      { indexed: true, name: 'subscriptionId', type: 'uint256' },
      { indexed: false, name: 'duration', type: 'uint32' },
      { indexed: false, name: 'paid', type: 'uint256' },
      { indexed: false, name: 'startedAt', type: 'uint64' },
      { indexed: false, name: 'expiresAt', type: 'uint64' },
    ],
  },
  {
    type: 'event',
    name: 'Transfer',
    inputs: [
      { indexed: true, name: 'from', type: 'address' },
      { indexed: true, name: 'to', type: 'address' },
      { indexed: true, name: 'tokenId', type: 'uint256' },
    ],
  },
  {
    type: 'event',
    name: 'Approval',
    inputs: [
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: true, name: 'approved', type: 'address' },
      { indexed: true, name: 'tokenId', type: 'uint256' },
    ],
  },
  {
    type: 'event',
    name: 'ApprovalForAll',
    inputs: [
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: true, name: 'operator', type: 'address' },
      { indexed: false, name: 'approved', type: 'bool' },
    ],
  },
  {
    type: 'event',
    name: 'MetadataUpdate',
    inputs: [{ indexed: false, name: 'tokenId', type: 'uint256' }],
  },
  {
    type: 'event',
    name: 'TierPriceUpdated',
    inputs: [
      { indexed: true, name: 'tier', type: 'uint8' },
      { indexed: false, name: 'priceUSD', type: 'uint128' },
    ],
  },
  {
    type: 'event',
    name: 'HookUpdated',
    inputs: [{ indexed: false, name: 'hook', type: 'address' }],
  },
  {
    type: 'event',
    name: 'Withdrawal',
    inputs: [
      { indexed: true, name: 'to', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { indexed: true, name: 'previousOwner', type: 'address' },
      { indexed: true, name: 'newOwner', type: 'address' },
    ],
  },
  {
    type: 'event',
    name: 'OwnershipTransferStarted',
    inputs: [
      { indexed: true, name: 'previousOwner', type: 'address' },
      { indexed: true, name: 'newOwner', type: 'address' },
    ],
  },
  {
    type: 'event',
    name: 'PriceFeedUpdated',
    inputs: [{ indexed: false, name: 'priceFeed', type: 'address' }],
  },
  {
    type: 'event',
    name: 'ProjectNameUpdated',
    inputs: [{ indexed: false, name: 'name', type: 'string' }],
  },
  {
    type: 'event',
    name: 'ProjectSymbolUpdated',
    inputs: [{ indexed: false, name: 'symbol', type: 'string' }],
  },
  {
    type: 'event',
    name: 'LogoUpdated',
    inputs: [],
  },
  {
    type: 'event',
    name: 'RendererUpdated',
    inputs: [{ indexed: false, name: 'renderer', type: 'address' }],
  },

  // --- Public functions ---
  {
    type: 'function',
    name: 'support',
    stateMutability: 'payable',
    inputs: [
      { name: 'recipient', type: 'address' },
      { name: 'tier', type: 'uint8' },
      { name: 'duration', type: 'uint32' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'grant',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'recipient', type: 'address' },
      { name: 'tier', type: 'uint8' },
      { name: 'duration', type: 'uint32' },
      { name: 'startAt', type: 'uint64' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'estimate',
    stateMutability: 'view',
    inputs: [
      { name: 'tier', type: 'uint8' },
      { name: 'duration', type: 'uint32' },
      { name: 'subscriber', type: 'address' },
    ],
    outputs: [
      { name: 'ethCost', type: 'uint256' },
      { name: 'adjustedDuration', type: 'uint32' },
    ],
  },
  {
    type: 'function',
    name: 'tierPeriods',
    stateMutability: 'view',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        components: [
          { name: 'tier', type: 'uint8' },
          { name: 'startedAt', type: 'uint64' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'currentTier',
    stateMutability: 'view',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [
      { name: 'tier', type: 'uint8' },
      { name: 'active', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'activeTokenOf',
    stateMutability: 'view',
    inputs: [{ name: 'supporter', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },

  // --- State getters ---
  {
    type: 'function',
    name: 'owner',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'pendingOwner',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'priceFeed',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'hook',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'projectName',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'projectSymbol',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'tierPrices',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint128' }],
  },
  {
    type: 'function',
    name: 'activeToken',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'subscriptions',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'createdAt', type: 'uint64' },
      { name: 'startedAt', type: 'uint64' },
      { name: 'expiresAt', type: 'uint64' },
    ],
  },
  {
    type: 'function',
    name: 'logo',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'renderer',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },

  // --- ERC-721 ---
  {
    type: 'function',
    name: 'name',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'symbol',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'totalSupply',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: '_owner', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'ownerOf',
    stateMutability: 'view',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'tokenURI',
    stateMutability: 'view',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'tokenOfOwnerByIndex',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'index', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'tokenByIndex',
    stateMutability: 'view',
    inputs: [{ name: 'index', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getApproved',
    stateMutability: 'view',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'isApprovedForAll',
    stateMutability: 'view',
    inputs: [
      { name: '_owner', type: 'address' },
      { name: 'operator', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
      { name: 'data', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'supportsInterface',
    stateMutability: 'view',
    inputs: [{ name: 'interfaceId', type: 'bytes4' }],
    outputs: [{ name: '', type: 'bool' }],
  },

  // --- Owner functions ---
  {
    type: 'function',
    name: 'acceptOwnership',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setPriceFeed',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_priceFeed', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setTierPrice',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'tier', type: 'uint8' },
      { name: 'priceUSD', type: 'uint128' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setHook',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_hook', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setProjectName',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_name', type: 'string' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setProjectSymbol',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_symbol', type: 'string' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setLogo',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_logo', type: 'string' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setRenderer',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_renderer', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'withdraw',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'transferOwnership',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newOwner', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'transferFrom',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'from', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setApprovalForAll',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'operator', type: 'address' },
      { name: 'approved', type: 'bool' },
    ],
    outputs: [],
  },
] as const
