service: support-indexer

image: <%= ENV["DOCKER_REGISTRY_USERNAME"] %>/support-indexer

servers:
  web:
    hosts:
      - <%= ENV["DEPLOY_HOST"] %>
    options:
      network: shared

proxy:
  ssl: true
  hosts:
    - <%= ENV["INDEXER_HOST"] %>
  app_port: 42069
  healthcheck:
    path: /ready
    interval: 5
    timeout: 300

deploy_timeout: 300

registry:
  username: <%= ENV["DOCKER_REGISTRY_USERNAME"] %>
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  context: ../..
  dockerfile: ../../Dockerfile.indexer

env:
  clear:
    PONDER_TELEMETRY_DISABLED: "true"
    SUPPORT_ADDRESS: "<%= ENV["SUPPORT_ADDRESS"] %>"
    SUPPORT_START_BLOCK: <%= ENV["SUPPORT_START_BLOCK"] %>
  secret:
    - PONDER_RPC_URL_1
    - DATABASE_URL
    - DATABASE_SCHEMA
    - PONDER_VIEWS_SCHEMA

accessories:
  db:
    image: postgres:17-alpine
    host: <%= ENV["DEPLOY_HOST"] %>
    port: "127.0.0.1:5435:5432"
    env:
      clear:
        POSTGRES_DB: ponder
        POSTGRES_USER: ponder
      secret:
        - POSTGRES_PASSWORD
    directories:
      - support_indexer_data:/var/lib/postgresql/data

ssh:
  user: root
